package org.pepetrace;

public enum ViewportRenderMode {
    SHADED,
    FLAT_SHADED,
    TEXTURELESS_SHADED,
    TEXTURELESS_FLAT_SHADED,
    ALBEDO,
    NORMAL,
    TANGENT,
    BITANGENT,
    GEOMETRIC_NORMAL,
    UV,
    INTERSECTION_COUNT,
    INTERSECTION_CHECKS,
}
